version: '2.2'

services:

  elasticsearch-app:
    build: .
    container_name: dclub
    ports:
      - "18080:8080"
      - "18089:8089"
    depends_on:
      - elasticsearch
    networks:
      - dclub-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
#      - discovery.seed_hosts=elasticsearch
#      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - dclub-network


